version: '3.8'

services:
  # ─── Instances du Serveur 1 ──────────────────────────────────────────────
  app1:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      - INSTANCE_ID=app1
      - PORT=3000
    networks:
      - happy-network

  app2:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      - INSTANCE_ID=app2
      - PORT=3000
    networks:
      - happy-network

  # ─── Nginx (Indispensable sur le S1) ─────────────────────────────────────
  nginx:
    image: nginx:1.25-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro # Si tu as tes certifs SSL ici
    depends_on:
      - app1
      - app2
    restart: unless-stopped
    networks:
      - happy-network

networks:
  happy-network:
    driver: bridge
